# 國中（冒險騎士）題庫：Learning Den 原創題目，依國一、國二、國三程度與會考題型編寫。
# 每題寫法：(題目, [正解, 誘答...], 解析)；正解一律寫第一個，產生時會固定打散選項順序。
# 用法：在 Magic_World_App 資料夾執行  python3 learning-den/tools/jh-bank.py
# 會把 learning-den/index.html 裡 JH_BANK_START/END 之間換成新的題庫。
import json, random, re, pathlib

J1V = [
 ("My father is a ____. He works in a hospital.", ["doctor", "farmer", "driver", "singer"], "doctor (n.) 醫生"),
 ("It's hot today. Let's go to the ____ and swim.", ["beach", "library", "bank", "museum"], "beach (n.) 海灘"),
 ("Amy is my father's sister. She is my ____.", ["aunt", "uncle", "cousin", "niece"], "aunt (n.) 姑姑；阿姨"),
 ("I'm ____. May I have some water?", ["thirsty", "hungry", "sleepy", "busy"], "thirsty (adj.) 口渴的"),
 ("We have English class on ____, the day after Monday.", ["Tuesday", "Sunday", "Friday", "Saturday"], "Tuesday (n.) 星期二"),
 ("The store opens at nine in the ____ and closes at ten at night.", ["morning", "evening", "afternoon", "weekend"], "morning (n.) 早上"),
 ("Put the milk in the ____. It keeps food cold.", ["refrigerator", "oven", "closet", "drawer"], "refrigerator (n.) 冰箱"),
 ("Ben is very ____. He is always kind to others.", ["friendly", "lazy", "rude", "noisy"], "friendly (adj.) 友善的"),
 ("My sister likes ____ class. She draws pictures every day.", ["art", "math", "science", "music"], "art (n.) 美術"),
 ("Please ____ the lights when you leave the room.", ["turn off", "turn on", "turn up", "turn around"], "turn off (phr.) 關掉（電燈、電器）"),
 ("This T-shirt is too ____. I need a smaller one.", ["big", "cheap", "short", "tight"], "big (adj.) 大的"),
 ("Kevin ____ his teeth after every meal.", ["brushes", "washes", "cuts", "combs"], "brush (v.) 刷"),
 ("There are four ____ in a year: spring, summer, fall, and winter.", ["seasons", "months", "weeks", "holidays"], "season (n.) 季節"),
 ("My grandma lives in the ____. There are many trees and farms there.", ["country", "city", "station", "hospital"], "country (n.) 鄉下"),
 ("The movie is very ____. Everyone is laughing.", ["funny", "boring", "scary", "sad"], "funny (adj.) 好笑的"),
 ("Don't ____ the street when the light is red.", ["cross", "clean", "close", "count"], "cross (v.) 穿越"),
 ("I take the ____ to school. It stops right in front of my house.", ["bus", "plane", "ship", "elevator"], "bus (n.) 公車"),
 ("Tom is very ____. He is 185 centimeters.", ["tall", "short", "young", "thin"], "tall (adj.) 高的"),
 ("Mom is cooking dinner in the ____.", ["kitchen", "bedroom", "bathroom", "garage"], "kitchen (n.) 廚房"),
 ("Our teacher is very ____. We must hand in our homework on time.", ["strict", "quiet", "sleepy", "afraid"], "strict (adj.) 嚴格的"),
 ("It's a ____ day. The sun is shining.", ["sunny", "rainy", "cloudy", "snowy"], "sunny (adj.) 晴朗的"),
 ("My favorite ____ is dumplings.", ["food", "sport", "color", "subject"], "food (n.) 食物"),
 ("The bookstore is ____ the bank and the post office.", ["between", "under", "behind", "into"], "between (prep.) 在…之間"),
 ("Look at the ____ on the wall. It's 3:15 now.", ["clock", "map", "door", "board"], "clock (n.) 時鐘"),
 ("We ____ our hands before we eat.", ["wash", "wear", "write", "watch"], "wash (v.) 洗"),
]
J1G = [
 ("Mary and her brother ____ in the same school.", ["are", "is", "am", "be"], "Mary and her brother 是複數主詞，be 動詞用 are。"),
 ("____ your parents teachers?", ["Are", "Is", "Do", "Does"], "主詞 your parents 是複數，問句用 Are。"),
 ("This is my new bike. ____ color is blue.", ["Its", "It's", "It", "Their"], "「它的」用所有格 Its；It's 是 It is。"),
 ("These books are ____. Please give them back to me.", ["mine", "my", "me", "I"], "mine = my books（所有格代名詞）。"),
 ("Jenny ____ breakfast at seven every morning.", ["eats", "eat", "eating", "is eat"], "主詞第三人稱單數＋現在簡單式，動詞加 s。"),
 ("My brother ____ like vegetables.", ["doesn't", "don't", "isn't", "aren't"], "第三人稱單數的否定：doesn't + 原形動詞。"),
 ("____ Tom play basketball after school? Yes, he does.", ["Does", "Do", "Is", "Are"], "回答用 does，問句就用 Does。"),
 ("Be quiet! The baby ____.", ["is sleeping", "sleeps", "sleep", "are sleeping"], "Be quiet! 表示此刻正在發生，用現在進行式。"),
 ("What ____ you doing now? I'm reading a comic book.", ["are", "do", "is", "does"], "現在進行式問句：What are you doing?"),
 ("____ open the window. It's cold.", ["Don't", "Doesn't", "Not", "No"], "否定祈使句：Don't + 原形動詞。"),
 ("There ____ some milk in the bottle.", ["is", "are", "be", "have"], "milk 是不可數名詞，用 There is。"),
 ("There ____ thirty students in our class.", ["are", "is", "has", "have"], "There are + 複數名詞。"),
 ("My cat can ____ very high.", ["jump", "jumps", "jumping", "to jump"], "can + 原形動詞。"),
 ("We don't have ____ homework today.", ["any", "some", "many", "a"], "否定句用 any；homework 不可數。"),
 ("Would you like ____ cookies?", ["some", "any", "a", "much"], "請別人吃東西的問句用 some。"),
 ("____ is that girl? She is my cousin, Lisa.", ["Who", "What", "Where", "Whose"], "問人是誰用 Who。"),
 ("____ pencil is this? It's Kevin's.", ["Whose", "Who", "What", "Where"], "問「誰的」用 Whose。"),
 ("____ do you go to school? By MRT.", ["How", "What", "When", "Why"], "問交通方式用 How。"),
 ("____ do you like summer? Because I can swim in the sea.", ["Why", "What", "Where", "How"], "回答 Because，問句用 Why。"),
 ("My birthday is ____ October 10th.", ["on", "in", "at", "for"], "特定日期前面用 on。"),
 ("Listen! Someone ____ at the door.", ["is knocking", "knocks", "knock", "are knocking"], "Listen! 表示正在發生，用現在進行式。"),
 ("Peter and I ____ good friends.", ["are", "is", "am", "be"], "Peter and I 是複數，用 are。"),
 ("How many ____ do you have? I have three.", ["brothers", "brother", "a brother", "brother's"], "How many + 複數名詞。"),
 ("How ____ is this cake? It's 80 dollars.", ["much", "many", "old", "long"], "問價錢用 How much。"),
 ("Let's ____ a movie tonight.", ["watch", "watching", "watches", "to watch"], "Let's + 原形動詞。"),
 ("She ____ her homework every night.", ["does", "do", "doing", "is do"], "主詞 She，do 要變成 does。"),
 ("Please give ____ a hand. The box is heavy.", ["me", "I", "my", "mine"], "動詞後面接受詞 me。"),
 ("The children ____ in the park now.", ["are playing", "is playing", "play", "plays"], "now 表示正在做；children 是複數，用 are + V-ing。"),
]
J2V = [
 ("The bread smells ____. Can I have a piece?", ["delicious", "terrible", "careful", "dangerous"], "delicious (adj.) 美味的"),
 ("Sam was ____ because he lost his wallet.", ["upset", "excited", "proud", "lucky"], "upset (adj.) 難過的；心煩的"),
 ("My parents gave me a bike as a birthday ____.", ["present", "problem", "promise", "plan"], "present (n.) 禮物"),
 ("The museum is ____ on Mondays, so we can't go in.", ["closed", "crowded", "famous", "empty"], "closed (adj.) 關閉的"),
 ("Wear a ____ when you ride a scooter. It keeps your head safe.", ["helmet", "scarf", "glove", "belt"], "helmet (n.) 安全帽"),
 ("Mr. Lin is a ____. He writes stories for children.", ["writer", "cook", "nurse", "pilot"], "writer (n.) 作家"),
 ("Don't be ____ to ask questions in class.", ["afraid", "glad", "full", "busy"], "afraid (adj.) 害怕的"),
 ("The ____ says it will rain hard tomorrow.", ["weather report", "menu", "map", "diary"], "weather report (n.) 氣象報告"),
 ("I need to ____ money for a new phone.", ["save", "spend", "waste", "lose"], "save (v.) 存（錢）"),
 ("The math test was so ____ that nobody finished it.", ["difficult", "easy", "short", "simple"], "difficult (adj.) 困難的"),
 ("Our class ____ the singing contest and got first prize.", ["won", "lost", "missed", "forgot"], "win (v.) 贏（過去式 won）"),
 ("Please ____ the trash into the right bin.", ["throw", "catch", "pick", "hold"], "throw (v.) 丟"),
 ("We went ____ in the mountains last weekend.", ["hiking", "shopping", "skating", "surfing"], "hiking (n.) 健行"),
 ("The little boy was ____ of the big dog.", ["scared", "sure", "full", "short"], "scared (adj.) 害怕的"),
 ("Mom ____ me to clean my room before dinner.", ["asked", "said", "spoke", "talked"], "ask sb. to V 要求某人做…"),
 ("Turn right at the ____, and you will see the park.", ["corner", "ceiling", "kitchen", "cloud"], "corner (n.) 轉角"),
 ("The concert was so ____. I want to go again!", ["exciting", "excited", "bored", "boring"], "exciting (adj.) 令人興奮的"),
 ("I forgot my umbrella, so I got ____ in the rain.", ["wet", "dry", "warm", "clean"], "wet (adj.) 濕的"),
 ("The ____ of the story is a brave little girl.", ["hero", "sound", "price", "reason"], "hero (n.) 主角；英雄"),
 ("Please speak ____. The baby is sleeping.", ["quietly", "loudly", "angrily", "quickly"], "quietly (adv.) 安靜地"),
 ("This jacket is on ____. It's only 300 dollars.", ["sale", "time", "fire", "duty"], "on sale 特價"),
 ("We need to ____ the classroom before the teacher comes.", ["clean up", "give up", "wake up", "grow up"], "clean up (phr.) 打掃乾淨"),
 ("The train was ____, so we waited for thirty minutes.", ["late", "early", "fast", "full"], "late (adj.) 遲的；誤點的"),
 ("Can I ____ your eraser? I'll give it back later.", ["borrow", "lend", "sell", "buy"], "borrow (v.) 借（入）"),
 ("He is ____ of his son because he won the race.", ["proud", "afraid", "tired", "full"], "be proud of 以…為榮"),
]
J2G = [
 ("I ____ my grandparents last Sunday.", ["visited", "visit", "visits", "will visit"], "last Sunday 用過去式。"),
 ("Where ____ you go yesterday?", ["did", "do", "were", "are"], "過去式的一般動詞問句用 did。"),
 ("She didn't ____ to the party last night.", ["go", "went", "goes", "going"], "didn't + 原形動詞。"),
 ("Tom ____ TV when his mom came home.", ["was watching", "is watching", "watches", "has watched"], "過去某個時間正在做：was/were + V-ing。"),
 ("It ____ rain tomorrow. Take an umbrella.", ["will", "is", "was", "did"], "tomorrow 用未來式 will + 原形動詞。"),
 ("We are going ____ a picnic this Saturday.", ["to have", "have", "having", "had"], "be going to + 原形動詞。"),
 ("My room is ____ than my sister's.", ["bigger", "big", "biggest", "more big"], "比較級：bigger than。"),
 ("This is the ____ movie I have ever seen.", ["most interesting", "more interesting", "interesting", "interestingest"], "最高級：the most interesting。"),
 ("Jack runs as ____ as his brother.", ["fast", "faster", "fastest", "more fast"], "as + 原級 + as。"),
 ("I want ____ a doctor in the future.", ["to be", "be", "being", "am"], "want to + 原形動詞。"),
 ("Kelly enjoys ____ in the ocean.", ["swimming", "swim", "to swim", "swims"], "enjoy + V-ing。"),
 ("Stop ____! The baby is sleeping.", ["talking", "talk", "talks", "talked"], "stop + V-ing：停止做某事。"),
 ("I stayed home ____ I was sick.", ["because", "so", "but", "or"], "because 表示原因。"),
 ("It was raining, ____ we didn't go out.", ["so", "because", "but", "if"], "so 表示結果。"),
 ("____ you study hard, you will pass the test.", ["If", "But", "Or", "So"], "If 如果。"),
 ("When I got home, my mom ____ dinner.", ["was cooking", "cooks", "is cooking", "cook"], "過去某個時間正在做，用過去進行式。"),
 ("He ____ late for school. He is a good student.", ["is never", "never is", "never does", "does never"], "頻率副詞放在 be 動詞後面。"),
 ("There ____ a lot of people in the park yesterday.", ["were", "was", "are", "is"], "yesterday 用過去式；people 是複數，用 were。"),
 ("I have a lot of homework ____ tonight.", ["to do", "doing", "did", "does"], "不定詞修飾名詞：homework to do。"),
 ("Which is ____, the sun or the moon?", ["bigger", "big", "biggest", "the biggest"], "兩者比較用比較級。"),
 ("She ____ to music when the phone rang.", ["was listening", "is listening", "listens", "will listen"], "電話響時她正在聽音樂，用過去進行式。"),
 ("Remember ____ the door when you leave.", ["to lock", "locking", "lock", "locked"], "remember to V：記得要去做。"),
 ("How long did it ____ you to finish the report?", ["take", "spend", "pay", "cost"], "It takes + 人 + 時間 + to V。"),
 ("I spent two hours ____ the book.", ["reading", "to read", "read", "reads"], "spend + 時間 + V-ing。"),
 ("Both Amy and I ____ good at math.", ["are", "am", "is", "be"], "Both A and B 當主詞是複數。"),
 ("Which season do you like ____, spring or fall?", ["better", "best", "good", "well"], "兩者之間選一個用 better。"),
 ("The children were ____ when they saw the clown.", ["excited", "exciting", "excite", "excites"], "人感到…用 -ed 形容詞。"),
 ("Mike is ____ boy in his class.", ["the tallest", "taller", "tallest", "the taller"], "三者以上比較用 the + 最高級。"),
]
J3V = [
 ("The earthquake ____ many buildings in the city.", ["damaged", "protected", "invented", "decorated"], "damage (v.) 損壞"),
 ("Recycling can help ____ the environment.", ["protect", "pollute", "destroy", "waste"], "protect (v.) 保護"),
 ("It's ____ to use your phone while you are driving.", ["dangerous", "necessary", "polite", "natural"], "dangerous (adj.) 危險的"),
 ("She practiced every day, and her hard work finally ____ off.", ["paid", "took", "gave", "turned"], "pay off (phr.) 有回報"),
 ("The ____ of this town has grown to 50,000.", ["population", "pollution", "position", "permission"], "population (n.) 人口"),
 ("He is an ____ person. He always tells the truth.", ["honest", "selfish", "careless", "jealous"], "honest (adj.) 誠實的"),
 ("We should ____ energy by turning off lights we don't use.", ["save", "waste", "burn", "create"], "save (v.) 節省"),
 ("The doctor gave me some ____ for my cough.", ["medicine", "furniture", "luggage", "traffic"], "medicine (n.) 藥"),
 ("The movie is based on a ____ event that happened in 1999.", ["real", "false", "silly", "future"], "real (adj.) 真實的"),
 ("Please ____ this form and give it back to me.", ["fill out", "find out", "give out", "run out"], "fill out (phr.) 填寫"),
 ("I'm ____ about the test tomorrow. I didn't study enough.", ["nervous", "relaxed", "proud", "bored"], "nervous (adj.) 緊張的"),
 ("The company decided to ____ more workers because business is good.", ["hire", "fire", "fail", "hide"], "hire (v.) 雇用"),
 ("The new MRT line makes it more ____ to travel around the city.", ["convenient", "expensive", "crowded", "difficult"], "convenient (adj.) 方便的"),
 ("He ____ to call me back, but he never did.", ["promised", "refused", "denied", "avoided"], "promise (v.) 答應"),
 ("The ____ between the two countries lasted for ten years.", ["war", "peace", "trip", "match"], "war (n.) 戰爭"),
 ("Tina has a good ____ of humor. Everyone likes her jokes.", ["sense", "taste", "smell", "sound"], "sense of humor 幽默感"),
 ("Smartphones have ____ the way people communicate.", ["changed", "cheated", "chased", "charged"], "change (v.) 改變"),
 ("Please keep ____. The movie is starting.", ["silent", "noisy", "busy", "hungry"], "silent (adj.) 安靜的"),
 ("Plastic bags take hundreds of years to ____.", ["break down", "break up", "break in", "break out"], "break down (phr.) 分解"),
 ("The team captain has the ____ to make final decisions.", ["power", "pain", "price", "prize"], "power (n.) 權力"),
 ("My grandfather is 90, but he still has a good ____.", ["memory", "mistake", "message", "member"], "memory (n.) 記憶力"),
 ("The flight was ____ because of the heavy snow.", ["canceled", "celebrated", "collected", "completed"], "cancel (v.) 取消"),
 ("I can't ____ which dress to buy. They are both pretty.", ["decide", "discover", "describe", "deliver"], "decide (v.) 決定"),
 ("The ____ of the novel is about a boy who travels through time.", ["plot", "pilot", "plate", "plant"], "plot (n.) 情節"),
 ("Volunteers ____ food to people in need.", ["provide", "prevent", "pretend", "predict"], "provide (v.) 提供"),
]
J3G = [
 ("I ____ in Taipei since 2020.", ["have lived", "lived", "live", "am living"], "since + 時間點，用現在完成式。"),
 ("____ you ever been to Japan?", ["Have", "Did", "Do", "Are"], "Have you ever been...? 用現在完成式問經驗。"),
 ("She has ____ finished her homework. She's watching TV now.", ["already", "yet", "ever", "still"], "肯定句的「已經」用 already。"),
 ("Has the bus arrived ____?", ["yet", "already", "since", "ago"], "疑問句「已經…了嗎」用 yet。"),
 ("We have been friends ____ ten years.", ["for", "since", "ago", "in"], "for + 一段時間。"),
 ("The window ____ by Tom yesterday.", ["was broken", "broke", "is broken", "breaks"], "被動語態過去式：was + 過去分詞。"),
 ("English ____ in many countries.", ["is spoken", "speaks", "is speaking", "spoke"], "被動語態：be + 過去分詞。"),
 ("The new library will ____ next year.", ["be built", "build", "built", "building"], "未來式被動：will be + 過去分詞。"),
 ("The girl ____ is standing by the door is my sister.", ["who", "which", "whose", "what"], "先行詞是人，關係代名詞用 who。"),
 ("This is the book ____ I bought yesterday.", ["that", "who", "what", "where"], "先行詞是物，用 that 或 which。"),
 ("I have a friend ____ father is a pilot.", ["whose", "who", "which", "that"], "表示「…的」的所有關係用 whose。"),
 ("Do you know where ____?", ["he lives", "does he live", "he does live", "lives he"], "間接問句用直述句語序。"),
 ("Can you tell me what time ____?", ["it is", "is it", "does it", "it does"], "間接問句：what time it is。"),
 ("You are a student, ____?", ["aren't you", "are you", "don't you", "isn't it"], "附加問句：肯定句配否定的附加問句。"),
 ("He can't swim, ____?", ["can he", "can't he", "does he", "doesn't he"], "否定句配肯定的附加問句。"),
 ("The box is so heavy ____ I can't carry it.", ["that", "to", "as", "than"], "so…that…：如此…以致於…"),
 ("She is too young ____ to school.", ["to go", "going", "go", "goes"], "too…to…：太…而不能…"),
 ("My grandpa ____ smoke, but he quit ten years ago.", ["used to", "is used to", "was used to", "uses to"], "used to + V：過去常常（現在不再）。"),
 ("I'm used to ____ up early.", ["getting", "get", "got", "gets"], "be used to + V-ing：習慣於…"),
 ("The movie was ____. I fell asleep.", ["boring", "bored", "bore", "bores"], "事物讓人覺得…用 -ing 形容詞。"),
 ("I don't know ____ to do next.", ["what", "that", "who", "why"], "疑問詞 + to V：what to do。"),
 ("It ____ me two hours to finish the puzzle.", ["took", "spent", "cost", "paid"], "It took + 人 + 時間 + to V。"),
 ("Not only Amy but also her parents ____ coming.", ["are", "is", "am", "be"], "not only A but also B，動詞跟 B 一致。"),
 ("The man ____ a red hat is my uncle.", ["wearing", "wears", "wore", "is wearing"], "現在分詞片語修飾名詞：the man wearing a red hat。"),
 ("Have you finished ____ the book?", ["reading", "to read", "read", "reads"], "finish + V-ing。"),
 ("He has lived here ____ he was a child.", ["since", "for", "ago", "during"], "since + 子句（過去式）。"),
 ("The letter ____ yet.", ["hasn't been sent", "didn't send", "isn't sending", "hasn't sent"], "現在完成式被動：has been + 過去分詞。"),
 ("This bridge ____ more than 100 years ago.", ["was built", "built", "has built", "is building"], "過去的被動語態：was + 過去分詞。"),
]
JCAP = [
 ("A: Could you pass me the salt?　B: ____", ["Sure. Here you are.", "No, I couldn't.", "Yes, I pass.", "That's all right."], "Here you are. 表示把東西遞給對方。"),
 ("A: I'm going to take the English test tomorrow.　B: ____", ["Good luck!", "Congratulations!", "Never mind.", "Help yourself."], "祝對方考試順利說 Good luck!"),
 ("A: Would you mind closing the window?　B: ____", ["Not at all.", "Yes, I close it.", "Of course I would.", "You're welcome."], "Would you mind...? 回答 Not at all. 表示不介意、願意做。"),
 ("A: What's wrong? You look pale.　B: ____", ["I have a stomachache.", "It's on the desk.", "I like it very much.", "That sounds great."], "What's wrong? 問對方怎麼了。"),
 ("A: How often do you go to the gym?　B: ____", ["Three times a week.", "For two hours.", "Last Sunday.", "By bus."], "How often 問頻率。"),
 ("A: How long have you studied English?　B: ____", ["For six years.", "Six years ago.", "In six years.", "Every six years."], "How long have you...? 用 for + 一段時間回答。"),
 ("A: Why don't we eat out tonight?　B: ____", ["That's a good idea.", "Because I'm hungry.", "No, we don't.", "I'm sorry to hear that."], "Why don't we...? 是提議，同意說 That's a good idea."),
 ("A: Excuse me, is this seat taken?　B: ____", ["No, go ahead.", "Yes, please sit down.", "I'll take it.", "It's my pleasure."], "座位沒人坐：No, go ahead."),
 ("A: I failed the math test again.　B: ____", ["Cheer up! You'll do better next time.", "Congratulations!", "Well done!", "Help yourself."], "安慰別人說 Cheer up!"),
 ("A: Hello. May I speak to Mr. Chen?　B: ____", ["Hold on, please.", "Yes, I can speak English.", "No, he doesn't.", "Take care."], "電話中請對方稍等：Hold on, please."),
 ("Notice: The school library will be closed from July 1 to July 10 for repairs.　Q: When can students borrow books again?", ["On July 11.", "On July 1.", "On July 10.", "Never."], "7/1 到 7/10 關閉，7/11 才能借書。"),
 ("Lisa got up late. She ran to the bus stop, but the bus had already left, so she took a taxi and got to school on time.　Q: How did Lisa go to school?", ["By taxi.", "By bus.", "On foot.", "By bike."], "文中說 she took a taxi。"),
 ("Tom: I'll be fifteen next Friday. My mom will make a big cake for me.　Q: What will happen next Friday?", ["It's Tom's birthday.", "Tom will buy a cake.", "Tom's mom will be fifteen.", "Tom will go shopping."], "Tom 下週五滿 15 歲，是他的生日。"),
 ("Sale! Buy one T-shirt for 300 dollars, and get the second one at half price.　Q: How much do two T-shirts cost?", ["450 dollars.", "300 dollars.", "600 dollars.", "150 dollars."], "第二件半價：300 + 150 = 450。"),
 ("Ken loves playing basketball, but he doesn't like watching it on TV. He thinks it's boring.　Q: Which is true?", ["Ken enjoys playing basketball.", "Ken likes watching basketball on TV.", "Ken thinks playing basketball is boring.", "Ken never plays sports."], "他喜歡打籃球，覺得看轉播很無聊。"),
 ("The zoo opens at 9:00 a.m. and closes at 5:00 p.m. The last ticket is sold at 4:00 p.m.　Q: Amy arrived at 4:30 p.m. What happened?", ["She couldn't buy a ticket.", "She got in for free.", "She stayed until 6:00 p.m.", "She bought the last ticket."], "最後售票 4:00，她 4:30 才到。"),
 ("Grandma: Remember to wear your coat. It's going to be cold this afternoon.　Q: What does Grandma want?", ["She wants the child to stay warm.", "She wants a new coat.", "She is feeling hot.", "She wants to go out."], "提醒穿外套，是希望孩子保暖。"),
 ("Class 801 collected 120 bottles, and Class 802 collected 90. Class 803 collected 30 more than Class 802.　Q: How many bottles did Class 803 collect?", ["120.", "90.", "30.", "150."], "802 收了 90，803 多 30，是 120。"),
 ("A: Is it far from here to the train station?　B: ____", ["It's about ten minutes on foot.", "It's at nine o'clock.", "It's very expensive.", "It's my favorite place."], "問距離，回答要走多久。"),
 ("A: Thank you for inviting me to dinner.　B: ____", ["My pleasure. Please come again.", "I'm full.", "Sorry, I can't.", "Here's the bill."], "別人道謝時說 My pleasure."),
 ("Many people ____ their old clothes to charity every year.", ["donate", "borrow", "steal", "repair"], "donate (v.) 捐贈"),
 ("Please ____ the paper in half.", ["fold", "fill", "float", "fail"], "fold (v.) 摺疊"),
 ("The concert was ____ because of the typhoon. It will be held next week instead.", ["put off", "put on", "taken off", "turned on"], "put off (phr.) 延期"),
 ("I can't find my key. I must have ____ it at school.", ["left", "leave", "leaving", "to leave"], "must have + 過去分詞：（過去）一定是…"),
 ("Jenny is the only student ____ got a perfect score.", ["who", "which", "whose", "what"], "先行詞是人，用 who。"),
 ("Sarah: I've read this novel three times, and I still love it!　Q: How does Sarah feel about the novel?", ["She loves it.", "She thinks it's boring.", "She hasn't read it.", "She wants to write it."], "讀了三次還是很愛。"),
 ("Pool rules: 1. Take a shower first. 2. No running. 3. Children under 10 must swim with an adult.　Q: Which is NOT allowed?", ["Running by the pool.", "Taking a shower.", "Swimming with an adult.", "Wearing a swimming cap."], "規則第 2 條：不准奔跑。"),
 ("A: Which do you prefer, tea or coffee?　B: ____", ["Tea, please.", "Yes, I do.", "Both of them aren't.", "I prefer."], "二選一的問題，直接說出選擇。"),
 ("The more you practice, the ____ you will become.", ["better", "good", "best", "well"], "the + 比較級…, the + 比較級…：越…就越…"),
 ("Mark's train leaves at 7:40. It takes him 20 minutes to walk to the station.　Q: What time should Mark leave home at the latest?", ["At 7:20.", "At 7:40.", "At 8:00.", "At 7:00."], "7:40 減 20 分鐘是 7:20。"),
]

def shuf(rows, seed):
    rnd = random.Random(seed); out = []
    for r in rows:
        opts = list(r[1]); ans = opts[0]; rnd.shuffle(opts)
        out.append([r[0], opts, opts.index(ans), r[2]])
    return out
def unit(id, grade, name, t, rows, seed, tag):
    u = {"id": id, "pub": "Learning Den 原創", "grade": grade, "name": name, "short": grade, "src": {t: name}, "tags": {t: tag}, "v": [], "g": [], "c": []}
    u[t] = shuf(rows, seed); return u
units = [
  unit("J1V", "國一", "國一　字彙", "v", J1V, 11, "字彙"), unit("J1G", "國一", "國一　文法", "g", J1G, 12, "文法"),
  unit("J2V", "國二", "國二　字彙", "v", J2V, 21, "字彙"), unit("J2G", "國二", "國二　文法", "g", J2G, 22, "文法"),
  unit("J3V", "國三", "國三　字彙", "v", J3V, 31, "字彙"), unit("J3G", "國三", "國三　文法", "g", J3G, 32, "文法"),
  unit("JCAP", "會考", "會考練習　對話・閱讀・綜合", "c", JCAP, 41, "會考"),
]
presets = [{"name": "國一全部", "ids": ["J1V", "J1G"]}, {"name": "國二全部", "ids": ["J2V", "J2G"]},
           {"name": "國三全部", "ids": ["J3V", "J3G"]}, {"name": "會考總複習（國一～國三＋會考）", "ids": [u["id"] for u in units]}]
p = pathlib.Path(__file__).parent.parent / "index.html"
s = p.read_text(encoding="utf-8")
block = "/* JH_BANK_START */\nconst JH_UNITS=" + json.dumps(units, ensure_ascii=False) + ";\nconst JH_PRESETS=" + json.dumps(presets, ensure_ascii=False) + ";\n/* JH_BANK_END */"
s = re.sub(r"/\* JH_BANK_START \*/.*?/\* JH_BANK_END \*/", lambda m: block, s, flags=re.S)
p.write_text(s, encoding="utf-8")
print("國中題庫：", sum(len(u["v"]) + len(u["g"]) + len(u["c"]) for u in units), "題")
